before_install:
  - sudo apt install -y python3-pip build-essential cmake default-jdk maven
  - git clone https://github.com/eclipse-cyclonedds/cyclonedds /tmp/cyclonedds
  - cd /tmp/cyclonedds && mkdir build && cd build && cmake ..  && make && sudo make install && cd $TRAVIS_BUILD_DIR
addons:
  apt:
    update: true

language: python
python:
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"

install:
  - travis_retry pip3 install tox
  - pip install codecov jsonpickle idl_parser
  - ./configure
  - cp tests/example.idl /tmp/example.idl
  - cp tests/helloworld.idl /tmp/helloworld.idl
script:
  - tox
cache:
  directories:
    - $HOME/.cache/pip
after_success:
- codecov
