before_install:
  - sudo apt install -y python3-pip build-essential cmake
  - git clone https://github.com/eclipse-cyclonedds/cyclonedds /tmp/cyclonedds
  - cd /tmp/cyclonedds && mkdir build && cd cmake --build . --target install
addons:
  apt:
    update: true

language: python3
python:
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"

install:
  - travis_retry pip3 install tox
  - pip install codecov jsonpickle idl_parser
script:
  - tox
cache:
  directories:
    - $HOME/.cache/pip
after_success:
- codecov